version: '3.8'
services:
  mongo1:
    image: mongo:5
    container_name: mongo1
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: testdb1
  mongo2:
    image: mongo:5
    container_name: mongo2
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: testdb2
